### ISSUE TITLE
Remove unused blocklists

### ISSUE THREAD

**Issue by englehardt** [mozilla-services/shavar-prod-lists#186]
We currently don't use:
* `adGuard-blacklist.json`
* `easyList-blacklist.json`
* `easyPrivacy-blacklist.json`
* `fanBoyAnnoyance-blacklist.json`
* `fanBoySocial-blacklist.json`

These were added for a test and are no longer needed. Might be nice to remove them + the corresponding config files to clean things up a bit.

**Comment by say-yawn** [comment]
@garvankeeley checking to see if any of your script is using these .JSON files.

**Comment by vesta0** [comment]
I agree that we should remove them.

**Comment by garvankeeley** [comment]
agreed, not used on iOS
