### ISSUE TITLE
Mozilla blocks GoSquared Chat widget

### ISSUE THREAD

**Issue by russellvaughan** [mozilla-services/shavar-prod-lists#198]
Hello! My name is Russell Vaughan and I'm a Sales Engineer at GoSquared. A client had raised that the Firefox's enhanced tracking protection now blocks our chat widget in strict mode as it is loaded from `gosquared.com` also, which is listed in your [blacklist](https://github.com/mozilla-services/shavar-prod-lists/search?q=gosquared&unscoped_q=gosquared). 

Our chat widget is not reliant on our Analytics tracking. If you block just our tracking endpoints, opposed to all of `gosquared.com`, our chat widget will still load and be functional. However, all tracking will still be blocked. We've worked with most of the other tracking blocking tools to solve this. 

Could we ask that you use  `data.gosquared.com` and `data2.gosquared.com` for your blacklist opposed to `gosquared.com`?

Please do let me know if you have any questions or need anything further.

**Comment by englehardt** [comment]
Thanks for reaching out Russel. Our list is managed by Disconnect and I see that you've already added a comment to their repo (https://github.com/disconnectme/disconnect-tracking-protection/issues/180). The disconnect folks can also be reached by email at support@disconnect.me.
