### ISSUE TITLE
Update license in .JSON files from Disconnect

### ISSUE THREAD

**Issue by say-yawn** [mozilla-services/shavar-prod-lists#223]
# About this Issue
After https://github.com/mozilla-services/shavar-prod-lists/pull/211 we have decided to move to `Attribution-NonCommercial-ShareAlike 4.0 International`. We should update the license key value pair in .JSON files from Disconnect

# Acceptance Criteria
- [x] Update license value in [disconnect-blocklist.json](https://github.com/mozilla-services/shavar-prod-lists/blob/master/disconnect-blacklist.json#L2)
- [x] Add license key value in disconnect-entitylist.json
- [x] Follow-up issue created on shavar-prod-lists to document structure change and script change https://github.com/mozilla-services/shavar-prod-lists/issues/249
- [x] Follow-up issue created on trackingprotection-tools repo to update entity processing https://github.com/mozilla/trackingprotection-tools/issues/18

**Comment by say-yawn** [comment]
Hey @patjack! While reviewing Shavar services I realized we did not update the license in the disconnect-blocklist.json and there was never a license key-value pair on the disconnect-entitylist.json. Can you please guide us/add a PR to update the licenses of these files? 

P.S. I checked the Disconnect repo for the [entities.json](https://github.com/disconnectme/disconnect-tracking-protection/blob/master/entities.json) to see if you all had license on that but you all also did not have license key-value pair for entities.

cc @englehardt

**Comment by patjack** [comment]
Hi @say-yawn,

Thanks for the ping on this! Yes, we should add the license to this file. I'm thinking we can follow the same form as the [blacklist](https://github.com/mozilla-services/shavar-prod-lists/pull/209/commits/972a73f095e24002bc31bcb6e87575a2d60bb97c) and have entities moved to an `entities` key. Like this:

```
{

"license": "Copyright 2010-2020..."
"entities" : { }
}
```

If that sounds good to you I can submit a PR w/these changes. Thanks!

**Comment by say-yawn** [comment]
Yes that sounds great! Thanks for following-up. It seems I'll have to make some changes to how we handle entities on the list creation script, would it be possible to create two separate PRs for adding the licenses in blocklist and entitylist respectively?

**Comment by patjack** [comment]
No problem! Those two PRs will be arriving shortly.

**Comment by say-yawn** [comment]
All the changes to licenses are now reflected on main and versioned branches.
