### ISSUE TITLE
Asking Yandex about images

### ISSUE THREAD

**Issue by msat-cont** [mozilla-services/shavar-prod-lists#34]
When "tracking protection" is enabled, I can not ask Yandex about images ( https://yandex.com/images/ ) via AJAX. I do not know if it is possible to allow it while still have the tracking disallowed. I encountered this issue when dealing with WebExtensions.

**Comment by cpeterso** [comment]
Thanks for reporting this issue. Is your WebExtension requesting images from Yandex or a web page? Can you share an example request URL that is blocked?

**Comment by msat-cont** [comment]
Hi, thanks for response; I'll explain what I try to do and how the calls are used for that. Notice that the WebExtension is currently in a polishing phase, working for me under Chromium (where I probably do not have any tracking protection), though with some hiccups under FF.

I try to provide a simple way for putting images into reverse-image-search web engines even when the images are served in a private URL (e.g. in a webmail interface where a user has to be logged in, thus putting just image URL to web-search engines would not work).

I do _not_ show the search results within WebExtension, since that would prevent the search providers to show their advertisements (and I understand that they need to pay their checks alike anyone else). That is, (at the end) a page is opened on sites of those search providers where users see the search results.

First I need to download the image (that is done via a common AJAX, and works when manifest has the proper site permission). Then it depends on particular web-search engines how one has to put the image to them. Since Firefox has broken sending from forms via POST method (when done at WebExtensions,  [see](https://bugzilla.mozilla.org/show_bug.cgi?id=1344465)), I do it via AJAX calls.

Regarding Yandex, the call to submit image data to perceptual search is a POST call to:
https://yandex.com/images/search?serpid=some_yandex_related_id&uinfo=sw-1600-sh-900-ww-1050-wh-668-pd-1-wp-16x9_1600x900&rpt=imageview&format=json&&request=%7B%22blocks%22%3A%5B%7B%22block%22%3A%22b-page_type_search-by-image__link%22%7D%5D%7D
with the data attached as a file data (name="upfile").
This call gets blocked.

That "some_yandex_related_id" string that is set there can be get e.g. via simple GET call to:
https://yandex.com/images/
where the "serpid" property is contained within the returned content.
This call gets blocked too. Notice that I tested the POST call above even without this call (since otherwise this GET call has to be done as the first call, to get the "serpid" string value).

In console, Firefox says:
"The resource at “https://yandex.com/images/” was blocked because tracking protection is enabled."

At the end, the user gets redirected (via window.location.replace(...)) into page with URL like:
https://yandex.com/images/search?url_returned_at_the_response_on_the_POST_call_above
Though it does not come to here for me under FF when tracking protection is set on (works otherwise).

**Comment by fmarier** [comment]
This seems like the same problem as https://bugzilla.mozilla.org/show_bug.cgi?id=1308640. The following might be useful: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions#Host_permissions

**Comment by msat-cont** [comment]
Mea culpa, mea maxima culpa. I completely missed this line in host permissions docs:
**"bypass tracking protection if the host is a full domain without wildcards."**
When being explicit (without wildcards) in manifest, it works as expected.
Thanks!
