### ISSUE TITLE
Identify Sanoma-owned publications and IdP as belonging to the same company

### ISSUE THREAD

**Issue by hsivonen** [mozilla-services/shavar-prod-lists#400]
`hs.fi` is a newspaper site owned by `sanoma.fi`. Subscribers log in on `tili.sanoma.fi` (as you can see by clicking "Kirjaudu" in the top right corner of `hs.fi`) and the login state is supposed to be reflected on `hs.fi`. With ETP in "strict" mode, `hs.fi` fails to discover the logged-in state if the login has been performed in an earlier session. This started happening in Firefox for iPad a couple of weeks earlier than it started happening in Fenix.

My undebugged hypothesis is that we treat `sanoma.fi` as a third party relative to `hs.fi` and strip the login cookie from requests to `sanoma.fi` (or block requests altogether) when `hs.fi` is the location bar domain.

Please add a same-entity annotation that allows `hs.fi` to perform cookieful requests to `sanoma.fi`.

While at it, it would make sense to also allow other `sanoma.fi` properties to make cookieful requests to the IdP. These are listed as linked logos on https://oma.sanoma.fi/v2/aihe/sanoma-tili/mika-on-sanoma-tili-ja-mihin-sita-kaytetaan

**Comment by englehardt** [comment]
It doesn't look like hs.fi or sanoma.fi are on the blocklist. The entitylist exceptions are only available for domains on the blocklist. I _suspect_ you're seeing this from partitioning, but I haven't tested it.

I copied your comments over to https://bugzilla.mozilla.org/show_bug.cgi?id=1678073 so the team can investigate.
