### ISSUE TITLE
Fraud and Security product placed on block list

### ISSUE THREAD

**Issue by ashley-campbell-iovation** [mozilla-services/shavar-prod-lists#455]
https://github.com/mozilla-services/shavar-prod-lists/blob/7eaadac98bc9dcc95ce917eff7bbb21cb71484ec/disconnect-blacklist.json#L7259

iovation/iesnare is a product in the fraud and security space. There is some confusion as to why this is on a blacklist when similar products are not on the list.

**Comment by englehardt** [comment]
Hello! Mozilla does not curate this blocklist; this repo is just used to stage Disconnect's list (https://github.com/disconnectme/disconnect-tracking-protection) for ingestion into Firefox . For questions about inclusion on the list, you can contact Disconnect at: support@disconnect.me.
