### ISSUE TITLE
Blocking googletagmanager.com breaks GCP Stackdriver console

### ISSUE THREAD

**Issue by ckolos** [mozilla-services/shavar-prod-lists#46]
Steps to reproduce in Nightly:

Navigate to GCP console
Login and Select "Monitoring" from the left menu
You will be redirected to a Stackdriver login page
Attempts to login will result in Shield + failure to follow link

**Comment by englehardt** [comment]
@ckolos can you tell if this is the same underlying issue as [Bug 1507055](https://bugzilla.mozilla.org/show_bug.cgi?id=1507055)?

**Comment by ckolos** [comment]
It sure reads the same and goes into much more depth. I suspected shavar due to the shield being shown during the operations and this site being the only one blocked. Setting disabling TP "makes things work", so perhaps not enough homework on my side.

**Comment by cosminstefanxp** [comment]
I'm also curious, why is GTM blocked. It's not doing tracking anything by itself. It's a tool for managing different JS based tools. If the tracking tools themselves are blocked (e.g. Google Analytics or Facebook Pixel), there's no reason to block Google Tag Manager.

My feeling is that this hurts the environment a lot. For example, via GTM, some websites might provide support features, based on user actions. This is not tracking in any way and the user ends up being hurt by this.

**Comment by englehardt** [comment]
Google tag manager was removed from Disconnect's list in https://github.com/disconnectme/disconnect-tracking-protection/commit/ac72379301ae4528f83e2110546b18e1d08d80d2. The stackdriver issue in Bug 1507055 was fixed, so I think we can close this issue.
