### ISSUE TITLE
Add webvisor.org on the blocklist

### ISSUE THREAD

**Issue by mik0l** [mozilla-services/shavar-prod-lists#583]
This is a Yandex domain it is already in the list of entities.

**Comment by gmvk** [comment]
You have the domain web-viser.org in the blocklist this domain you missed.

**Comment by gmvk** [comment]
You have the domain **web-visor.com** in the blocklist this domain you missed.

**Comment by gmvk** [comment]
You have the webvisor.com domain on the blacklist, but for some reason you missed the webvisor.org domain.

**Comment by gmvk** [comment]
You have the web-visor.com domain on the blacklist, but for some reason you missed the webvisor.org domain.

**Comment by gmvk** [comment]
You have the `web-visor.com` domain on the blacklist, but for some reason you missed the `webvisor.org` domain.

**Comment by gmvk** [comment]
You blacklisted `web-visor.com`, but for some reason you missed `webvisor.org`.
