### ISSUE TITLE
Interenet Brands and WSS connections

### ISSUE THREAD

**Issue by damijank** [mozilla-services/shavar-prod-lists#607]
Hi,

I'm writing on behalf of Internet Brands.

Our website editor has had an upgrade a couple of months ago. Now it uses a WebSockets connection to synchronize some information between multiple browser sessions for same site editing. In Firefox, when the user has the **Enhaned Tracking Protection** set to **Strict**, the browser blocks the connection to the WebSockets server **_wss://smbwebmgr-sockets.internetbrands.com_** .

In the **disconnect-blacklist.json** file, there in an entry for the **_internetbrands.com_** domain, which obviously blocks ALL (?) subdomains, too. I'm pretty certain that this entry is too broad. Effectively, on all subdomains of the domain, it disables everything for which this list is used for (obviously WS connections are one use case). https://github.com/mozilla-services/shavar-prod-lists/blob/master/disconnect-blacklist.json#L5300

Is this the right place to report this? If not, please advise where to turn to.

**Comment by Trikolon** [comment]
The list is curated by Disconnect, you can submit an appeal here: https://disconnect.me/trackerprotection#submissions_and_appeals

**Comment by damijank** [comment]
Thanks!
