### ISSUE TITLE
JSECOIN should not be included in this code, because it's a 100% Opt-In Miner

### ISSUE THREAD

**Issue by ecnels** [mozilla-services/shavar-prod-lists#64]
Because JSECOIN is 100%, explicit USER-OPT-IN, users will always be asked whether they want their CPU used for mining at JSECOIN-hosted-sites. If this were to be allowed as the Default behavior of Firefox the user would not be able to distinguish between User-Approved (Safe) Miners and unsafe Miners that steal CPU Cycles.  Web Hoster and User Consents are the first principles of JSECOIN Design (and perhaps existing or future other Miners too).

Eventually, it may be useful to provide a Checkbox (or equivalent) that By-Default allows Opt-In Miners, because Opting-In should be the user’s choice. It’s the secret monetizing by stealing user CPU cycles that is to be discouraged, not legitimate means of monetizing anything with which users explicitly agree.  JSECOIN needs to be removed from this code.

**Comment by englehardt** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1547001#c6
