### ISSUE TITLE
Trackers still coming through on NBC / AMP

### ISSUE THREAD

**Issue by amtopel** [mozilla-services/shavar-prod-lists#68]
Example: https://www.google.com/amp/s/www.nbcnews.com/news/amp/ncna1027251

**Comment by englehardt** [comment]
Thanks for the report. I see that you've [already reported this on Disconnect's upstream repo](https://github.com/disconnectme/disconnect-tracking-protection/issues/86), which is the right place for unblocked tracker / re-classification requests.
