### ISSUE TITLE
Remove the Disconnect category

### ISSUE THREAD

**Issue by englehardt** [mozilla-services/shavar-prod-lists#69]
The "Disconnect" category is currently remapped to the Advertising, Analytics, and Social categories using [this file](https://github.com/mozilla-services/shavar-list-creation/blob/master/disconnect_mapping.json). This adds [complexity](https://github.com/mozilla/trackingprotection-tools/blob/b5872e2bdcce2789db6b586fc2adf7e436a15748/trackingprotection_tools/DisconnectParser.py#L106-L143) to list parsing, and has led to a lot of confusion when folks look at the plaintext version of the list. We should remove this category from the upstream list if possible.

**Comment by englehardt** [comment]
@patjack is there any reason we need to keep the `Disconnect` category around?

**Comment by patjack** [comment]
@englehardt right now our extensions use the `Disconnect` category but we have been planning to migrate away from it. I agree it does add some complexity and is a little confusing when just looking at the plaintext version. We can export a version of the list that is remapped so you don't have to do it on your side. Does that sound good to you?

**Comment by englehardt** [comment]
This is definitely low priority from our side, so if you have a reason to keep it around or if it's too much work to remap on export feel free to keep it as is. Do you have a timeline for the migration?

**Comment by patjack** [comment]
We don't have a timeline yet but I can add the remapping to our export script. That way you won't have to continue to categorize and remap new domains that are added in the category. I'll give you a ping here when I create the PR with the `Disconnect` category removed.

**Comment by englehardt** [comment]
@patjack Is there any chance you'd be able to integrate the remapping of this category sometime over the next few weeks?

**Comment by patjack** [comment]
Hi @englehardt - yes, definitely. We'll have the category removed and mapped appropriately for PRs to this repo. We should have this change by mid next week and I'll submit a new PR for you to test. Note: our main repo: https://github.com/disconnectme/disconnect-tracking-protection, will still have the `Disconnect` category for now to maintain compatibility with our extensions.

**Comment by englehardt** [comment]
This was merged in #110 with follow up work filed in #111
