### ISSUE TITLE
ibm.com is too general to be considered a tracking domain

### ISSUE THREAD

**Issue by FrivalszkyP** [mozilla-services/shavar-prod-lists#74]
I'm a developer at IBM and the product I'm working on is embeddable on third-party sites. 

`ibm.com` was added to the list of services here: https://github.com/mozilla-services/shavar-prod-lists/blame/master/disconnect-blacklist.json

FYI I saw that it was lifted from the disconnectme/disconnect-tracking-protection repo by the original developer (@carbureted) so I created an issue in that repo as well.

I think this was an oversight since tracking and analytics services are not the sole offerings of IBM. Please remove ibm.com from the list, or change it to the specific offending subdomain(s).

Thank you!

**Comment by groovecoder** [comment]
Hi, thanks for filing the issue. You'll need to copy this issue "upstream" into Disconnect's tracking protection repository:

https://github.com/disconnectme/disconnect-tracking-protection
