### ISSUE TITLE
Temporarily revert Google entity list expansion to fix shavar breakage

### ISSUE THREAD

**Issue by englehardt** [mozilla-services/shavar-prod-lists#81]
We need to revert the changes in https://github.com/disconnectme/disconnect-tracking-protection/commit/f2550bc3025babf6b844927e7a3acbe65e5ba3d3 that were added for the reasons described in https://github.com/disconnectme/disconnect-tracking-protection/issues/100. These changes push the generated entity list over the url classifier's [chunk size limit](https://searchfox.org/mozilla-central/rev/11d9c7b7fa82fdfb8ac2a8f0864e9d8d5fe2b926/toolkit/components/url-classifier/ProtocolParser.cpp#252), which is causing all Firefox clients to fail to update any tracking protection list.

The next steps here are to:
- [x] Revert the Google entity list changes.
- [x] Create a new whitelist similar in configuration to [`mozstd-trackwhite-digest256`](https://github.com/mozilla-services/shavar-list-creation-config/blob/d55229f2b711d0f28931193d57d15d8c74035075/stage.ini#L105-L108), perhaps `mozstd-trackwhite-google-digest256`.
- [x] Duplicate the Google entity over to that whitelist.
- [x] Consume the new whitelist alongside the standard whitelist in all channels and for [all classifier features](https://searchfox.org/mozilla-central/search?q=mozstd-trackwhite-digest256&path=).
- [x] Exclude the Google entity from `mozstd-trackwhite-digest256`.
- [x] Add the changes from this PR back into the main list

**Comment by englehardt** [comment]
For some context, we also considered:
1. Increasing the maximum chunk size in the url-classifier
2. Migrating the shavar service to serve the list in multiple chunks.

We chose not to do (1) since it's unclear to what level we should increase the limit. We're kinda abusing the safebrowsing v2 protocol by sticking the entire list in a single "chunk", and increasing that chunk size seems like a further abuse.

We would achieve a similar result with (2) to the approach I'm suggesting in my initial comment, but it would require quite a bit more work. We [don't publish deltas](https://github.com/mozilla-services/shavar/blob/e18822c2dfbd26f2df25e091ec4dad0505251042/shavar/views/__init__.py#L137-L149) for any of the tracking protection lists, so the current server code is set up to expect a single chunk. We'd need to migrate that over to expect multiple adds (but not diffs). The list creation and publishing scripts [all expect](https://github.com/mozilla-services/shavar-list-creation/blob/4b4a9955ab9b9fcdc583e06066c957506958c2bd/publish2cloud.py#L133-L165) lists to be identified as a single chunk, so we'd need to update them as well.

With our desire to move to remote settings, making any changes to the shavar service seems like a waste of time. Since we have incremental updates on our roadmap, we should revisit this question in that context. Assuming the url classifier continues to use the safebrowsing v2 protocol, publishing incremental updates will require us to move to diffs / multiple chunks. We may get this for free as part of that work.

**Comment by englehardt** [comment]
https://github.com/mozilla-services/shavar-prod-lists/pull/80 landed to revert the new additions

**Comment by skim1102** [comment]
https://github.com/mozilla-services/shavar-list-creation/pull/109 created a separate file for google entities `google-trackwhite-digest256`
